version: "3.8"
services:
  db-postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: "fit_today"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "#15Gjcn3128Uh.#"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/always-initdb.d:/always-initdb.d
    ports:
      - 5432:5432
    restart: always
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]

volumes:
  postgres_data: